language: php
dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

php:
    - '7.0'
    - '7.1'

matrix:
    fast_finish: true
    include:
        - php: hhvm
    allow_failures:
        - php: nightly
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

sudo: true

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS knorke;'
    - composer require satooshi/php-coveralls:* --ignore-platform-reqs
    - travis_retry composer install --dev --no-interaction --ignore-platform-reqs
    # hack to tell HHVM to act like PHP 7
    # - https://github.com/sebastianbergmann/phpunit/issues/2581#issuecomment-299598923
    # - https://docs.travis-ci.com/user/languages/php/ (see custom PHP configuration)
    - echo "hhvm.php7.all=1" >> /tmp/hhvm.php.ini
    - ls /home/travis/.phpenv/
    - ls /home/travis/.phpenv/versions/
    - ls /home/travis/.phpenv/versions/hhvm/
    - ls /home/travis/.phpenv/versions/hhvm/etc/
    - mkdir /home/travis/.phpenv/versions/hhvm/etc/conf.d
    - phpenv config-add /tmp/hhvm.php.ini

script: vendor/bin/phpunit --bootstrap tests/bootstrap-travis.php --coverage-clover gen/coverage/clover.xml

after_script: php vendor/bin/coveralls -v
